import { writeFile } from "node:fs/promises";
import { books } from "../src/data/parsedBooks.js";

const OPEN_LIBRARY_COVER = (isbn) =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-M.jpg?default=false`;
const OPEN_LIBRARY_ID_COVER = (coverId) =>
  `https://covers.openlibrary.org/b/id/${coverId}-L.jpg?default=false`;
const AMAZON_COVER = (identifier) =>
  `https://images-na.ssl-images-amazon.com/images/P/${identifier}.01.LZZZZZZZ.jpg`;

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function fetchJson(url) {
  for (let attempt = 0; attempt < 3; attempt += 1) {
    try {
      const response = await fetch(url, {
        headers: { "User-Agent": "my-reading-cover-import/1.0" },
        signal: AbortSignal.timeout(5000),
      });
      if (response.ok) return response.json();
      if (response.status === 429) await sleep(1000 * (attempt + 1));
    } catch {
      await sleep(500 * (attempt + 1));
    }
  }
  return null;
}

async function coverExists(url) {
  try {
    const response = await fetch(url, {
      method: "HEAD",
      headers: { "User-Agent": "my-reading-cover-import/1.0" },
      signal: AbortSignal.timeout(5000),
    });
    return response.ok;
  } catch {
    return false;
  }
}

async function amazonCoverExists(url) {
  try {
    const response = await fetch(url, {
      method: "HEAD",
      headers: { "User-Agent": "my-reading-cover-import/1.0" },
      signal: AbortSignal.timeout(5000),
    });
    return response.ok && response.headers.get("content-type")?.includes("image/jpeg");
  } catch {
    return false;
  }
}

async function withConcurrency(items, limit, worker) {
  const results = [];
  let next = 0;
  async function run() {
    while (next < items.length) {
      const index = next++;
      results[index] = await worker(items[index], index);
    }
  }
  await Promise.all(Array.from({ length: limit }, run));
  return results;
}

function identifierFromLink(link) {
  return link.match(/(?:\/dp\/|\/product\/)([A-Z0-9]{10})(?:[/?]|$)/i)?.[1] || null;
}

function normalize(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "")
    .replace(/the|a|an/g, "");
}

const results = Object.create(null);
const identifierBooks = books
  .map((book) => ({ book, identifier: identifierFromLink(book.link) }))
  .filter(({ identifier }) => identifier && /^\d{9}[\dX]$|^\d{13}$/.test(identifier));

const directMatches = await withConcurrency(identifierBooks, 12, async ({ book, identifier }) => {
  const url = OPEN_LIBRARY_COVER(identifier);
  if (await coverExists(url)) return { title: book.title, url };
  return null;
});

for (const match of directMatches.filter(Boolean)) results[match.title] = match.url;
console.log(`Open Library ISBN covers: ${Object.keys(results).length}/${books.length}`);

const amazonCandidates = books
  .filter((book) => !results[book.title])
  .map((book) => ({ book, identifier: identifierFromLink(book.link) }))
  .filter(({ identifier }) => identifier);
const amazonMatches = await withConcurrency(amazonCandidates, 12, async ({ book, identifier }) => {
  const url = AMAZON_COVER(identifier);
  return (await amazonCoverExists(url)) ? { title: book.title, url } : null;
});
for (const match of amazonMatches.filter(Boolean)) results[match.title] = match.url;
console.log(`After Amazon image fallback: ${Object.keys(results).length}/${books.length}`);

if (process.env.SKIP_FALLBACKS === "1") {
  const lines = [
    "// Generated by scripts/generateBookCovers.mjs.",
    "// Sources: Open Library Covers API and Amazon product images.",
    "export const bookCovers = {",
    ...Object.entries(results)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([title, url]) => `  ${JSON.stringify(title)}: ${JSON.stringify(url)},`),
    "};",
    "",
  ];
  await writeFile(new URL("../src/data/bookCovers.js", import.meta.url), lines.join("\n"));
  process.exit(0);
}

const misses = books.filter((book) => !results[book.title]);
const searchMatches = await withConcurrency(misses, 6, async (book) => {
  const params = new URLSearchParams({
    title: book.title,
    author: book.author,
    limit: "5",
    fields: "title,author_name,cover_i",
  });
  const data = await fetchJson(`https://openlibrary.org/search.json?${params}`);
  const docs = data?.docs || [];
  const wantedTitle = normalize(book.title);
  const match = docs.find((doc) => normalize(doc.title || "") === wantedTitle) || docs[0];
  return match?.cover_i ? { title: book.title, url: OPEN_LIBRARY_ID_COVER(match.cover_i) } : null;
});

for (const match of searchMatches.filter(Boolean)) results[match.title] = match.url;
console.log(`After Open Library title search: ${Object.keys(results).length}/${books.length}`);

const googleMisses = books.filter((book) => !results[book.title]);
const googleMatches = await withConcurrency(googleMisses, 12, async (book) => {
  const query = `intitle:${book.title} inauthor:${book.author}`;
  const params = new URLSearchParams({ q: query, maxResults: "5" });
  const data = await fetchJson(`https://www.googleapis.com/books/v1/volumes?${params}`);
  const wantedTitle = normalize(book.title);
  const match = (data?.items || []).find((item) => {
    const candidate = normalize(item.volumeInfo?.title || "");
    return candidate === wantedTitle || candidate.includes(wantedTitle) || wantedTitle.includes(candidate);
  });
  const image = match?.volumeInfo?.imageLinks?.thumbnail;
  return image ? { title: book.title, url: image.replace(/^http:/, "https:") } : null;
});

for (const match of googleMatches.filter(Boolean)) results[match.title] = match.url;
console.log(`After Google Books fallback: ${Object.keys(results).length}/${books.length}`);

const lines = [
  "// Generated by scripts/generateBookCovers.mjs.",
  "// Sources: Open Library Covers API and Google Books API.",
  "export const bookCovers = {",
  ...Object.entries(results)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([title, url]) => `  ${JSON.stringify(title)}: ${JSON.stringify(url)},`),
  "};",
  "",
];
await writeFile(new URL("../src/data/bookCovers.js", import.meta.url), lines.join("\n"));
